# Generated by Django 2.2 on 2019-07-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='img',
            new_name='profile_image',
        ),
    ]
