# Generated by Django 2.2 on 2019-07-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20190730_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
